version: '3'

services: 
  db:
    image: mongo:5
    ports: 
      - 27019:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - mongodata:/data/db       
volumes:
  mongodata:      